[package]
name = "rdp_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.3.2"
brzlog_rs = { git = "https://github.com/zklrv/brzlog_rs.git" }

[build-dependencies]
slint-build = "1.3.2"
